### PR TITLE
Harvard fix cow bought bug

### LINKED ISSUE #29: FIX BUG: Toast says "Cow sold!" even when no cow was sold
# Overview
When selling cows, if you run out of money, the app doesn't let you continue to sell cows. However, the toast message that pops up says "Cow sold!" even if you didn't just sell a cow.

Perhaps the toast should NOT pop up when you successfully sell a cow (since you already see the number of cows go up, and your money go down), but should ONLY pop up when try to sell a cow but don't have any.. and in that case, the message should indicate that.

# Steps to reproduce

1. Join a commons
2. Try to sell a cow. See toasts that say "Cow sold!"

- Expected: a toast that says something like: "You can't sell a cow because you don't have any cows"
- Observed: a toast that says "Cow sold!"

Image

### PR DESCRIPTION
**Pull request by HarvardWang**
Closes #29 

- [x] Added Exceptions for NotEnoughMoney and NoCows, 
- [x] App properly catches these exceptions and displays correct toast message
- [x] Added exception handler to `ApiController.java`
- [x]  Updated tests in `UserCommonsController.java` that check for correct error status and exception, and that commons is maintained

### CODE REVIEW

**Review by josiahnross — APPROVED** [review]
LGTM!

**Review by pconrad — APPROVED** [review]
LGTM.. will test on QA before merging.

**Review by pconrad — CHANGES_REQUESTED** [review]
This is all good work!  The trouble is: the bugs are still there!

Look at the original bug report.   If you deploy these changes (which I did) and try the steps in the original bug report *absolutely nothing has changed*.  You still see a toast that says "Cow Bought" (when no cow was bought) and you still see a message that says "Cow Sold" when no cow was sold.)

These changes are good, and I would suggest keeping them.  It's good to secure the backend as welll and offer good error messages.  BUT, you also need to write some frontend code.

I suggest NOT having a toast at all when the cow purchase or sale is successful, but ONLY when there is an error (not enough money, or not enough cows).  You don't necessarily need to submit the request to the backend; you can do the check with data available to you in the frontend, and just never submit the request in the first place.

If you do both front end and backend, AND get the toasts right, this is a 20 point issue.

**Review by pconrad — APPROVED** [review]
LGTM... nice work!

**Pull request merged**
