### PR TITLE
ak - adding pc's changes from 6pm happycows

### PR DESCRIPTION
**Pull request by Gopu2001**
From https://github.com/ucsb-cs156-f22/f22-6pm-happycows/pull/37:
In this PR, we fix the CommonsTable so that it correctly pulls information from the /allplus endpoint.

When the endpoint was changed from /all to /allplus, the shape of the JSON changed, but the CommonsTable wasn't updated. This PR fixes that.

We go from (screenshot from the [f22-5pm heroku site](https://f22-5pm-3-happycows.herokuapp.com/)):
Screenshot 2022-11-27 at 8 00 53 PM (1)

To (screenshot from localhost, so different commons):
Screenshot 2022-11-27 at 10 14 16 PM

### CODE REVIEW

**Comment by Gopu2001** [comment]
This PR will be blocked until #38 gets merged in.

**Review by josiahnross — APPROVED** [review]
LGTM!

**Review by pconrad — APPROVED** [review]
LGTM.   I'll rebase on main, which should fix the CI/CD failures, I hope, and test on qa before merging.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
