### PR TITLE
38 AK add tests to make the stryker mutation and jest coverage 100

### LINKED ISSUE #38: Add tests to make the stryker mutation and jest coverage 100%
# Coverage Issue

Image

# Mutation Issues
Image

image

# Steps to reproduce
Run `npx stryker run` and observe the mutation test showing that one of Footer.js's mutations is not killed.

### PR DESCRIPTION
**Pull request by Gopu2001**
# Implementation Notes
 * Deleted `JobsComingSoon.js`
 * Added tests for coverage on the Footer for the optional chaining

Closes #38

### CODE REVIEW

**Comment by Gopu2001** [comment]
Output from `npx stryker run`:
```
Ran 11.66 tests per mutant on average.
-----------------------------|---------|----------|-----------|------------|----------|---------|
File                         | % score | # killed | # timeout | # survived | # no cov | # error |
-----------------------------|---------|----------|-----------|------------|----------|---------|
All files                    |  100.00 |      360 |         0 |          0 |        0 |       0 |
 components                  |  100.00 |      197 |         0 |          0 |        0 |       0 |
  Commons                    |  100.00 |       48 |         0 |          0 |        0 |       0 |
   CommonsCard.js            |  100.00 |        8 |         0 |          0 |        0 |       0 |
   CommonsForm.js            |  100.00 |        2 |         0 |          0 |        0 |       0 |
   CommonsList.js            |  100.00 |        5 |         0 |          0 |        0 |       0 |
   CommonsOverview.js        |  100.00 |        8 |         0 |          0 |        0 |       0 |
   CommonsPlay.js            |  100.00 |        2 |         0 |          0 |        0 |       0 |
   CommonsTable.js           |  100.00 |        3 |         0 |          0 |        0 |       0 |
   FarmStats.js              |  100.00 |        1 |         0 |          0 |        0 |       0 |
   ManageCows.js             |  100.00 |        6 |         0 |          0 |        0 |       0 |
   Profits.js                |  100.00 |        3 |         0 |          0 |        0 |       0 |
   ProfitsTable.js           |  100.00 |       10 |         0 |          0 |        0 |       0 |
  Jobs                       |  100.00 |       27 |         0 |          0 |        0 |       0 |
   InstructorReportForm.js   |  100.00 |        1 |         0 |          0 |        0 |       0 |
   JobsTable.js              |  100.00 |       21 |         0 |          0 |        0 |       0 |
   MilkCowsJobForm.js        |  100.00 |        1 |         0 |          0 |        0 |       0 |
   TestJobForm.js            |  100.00 |        3 |         0 |          0 |        0 |       0 |
   UpdateCowHealthForm.js    |  100.00 |        1 |         0 |          0 |        0 |       0 |
  Leaderboard                |  100.00 |       20 |         0 |          0 |        0 |       0 |
   LeaderboardTable.js       |  100.00 |       20 |         0 |          0 |        0 |       0 |
  Nav                        |  100.00 |       26 |         0 |          0 |        0 |       0 |
   AppNavbar.js              |  100.00 |       23 |         0 |          0 |        0 |       0 |
   AppNavbarLocalhost.js     |  100.00 |        1 |         0 |          0 |        0 |       0 |
   Footer.js                 |  100.00 |        2 |         0 |          0 |        0 |       0 |
  Profile                    |  100.00 |        6 |         0 |          0 |        0 |       0 |
   RoleBadge.js              |  100.00 |        6 |         0 |          0 |        0 |       0 |
  Users                      |  100.00 |       19 |         0 |          0 |        0 |       0 |
   UsersTable.js             |  100.00 |       19 |         0 |          0 |        0 |       0 |
  Utils                      |  100.00 |       11 |         0 |          0 |        0 |       0 |
   Plaintext.js              |  100.00 |       11 |         0 |          0 |        0 |       0 |
  OurTable.js                |  100.00 |       40 |         0 |          0 |        0 |       0 |
 layouts                     |  100.00 |        1 |         0 |          0 |        0 |       0 |
  BasicLayout                |  100.00 |        1 |         0 |          0 |        0 |       0 |
   BasicLayout.js            |  100.00 |        1 |         0 |          0 |        0 |       0 |
 pages                       |  100.00 |       51 |         0 |          0 |        0 |       0 |
  AdminCreateCommonsPage.js  |  100.00 |       10 |         0 |          0 |        0 |       0 |
  AdminEditCommonsPage.js    |  100.00 |       20 |         0 |          0 |        0 |       0 |
  AdminJobsPage.js           |  100.00 |        5 |         0 |          0 |        0 |       0 |
  AdminListCommonPage.js     |  100.00 |        1 |         0 |          0 |        0 |       0 |
  AdminUsersPage.js          |  100.00 |        1 |         0 |          0 |        0 |       0 |
  HomePage.js                |  100.00 |        1 |         0 |          0 |        0 |       0 |
  LeaderboardPage.js         |  100.00 |        1 |         0 |          0 |        0 |       0 |
  LoginPage.js               |  100.00 |        2 |         0 |          0 |        0 |       0 |
  NotFoundPage.js            |  100.00 |        1 |         0 |          0 |        0 |       0 |
  PlayPage.js                |  100.00 |        1 |         0 |          0 |        0 |       0 |
  ProfilePage.js             |  100.00 |        8 |         0 |          0 |        0 |       0 |
 utils                       |  100.00 |      111 |         0 |          0 |        0 |       0 |
  arrayUtils.js              |  100.00 |        2 |         0 |          0 |        0 |       0 |
  commonsUtils.js            |  100.00 |        6 |         0 |          0 |        0 |       0 |
  currentUser.js             |  100.00 |       39 |         0 |          0 |        0 |       0 |
  dateUtils.js               |  100.00 |       10 |         0 |          0 |        0 |       0 |
  leaderboardSortingUtils.js |  100.00 |        9 |         0 |          0 |        0 |       0 |
  systemInfo.js              |  100.00 |       15 |         0 |          0 |        0 |       0 |
  useBackend.js              |  100.00 |       20 |         0 |          0 |        0 |       0 |
  users.js                   |  100.00 |       10 |         0 |          0 |        0 |       0 |
-----------------------------|---------|----------|-----------|------------|----------|---------|
19:36:12 (80731) INFO MutationTestReportHelper Final mutation score of 100.00 is greater than or equal to break threshold 100
```

**Review by Geivet — APPROVED** [review]
LGTM!

**Comment by Gopu2001** [comment]
> LGTM!

Awesome, thanks @Geivet!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
